name: Build Distribution

on:
  push:
    branches:
      - octocat-patch-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build and package with Gradle
        run: ./gradlew bootJar
        
      - name: Show structure of artifact files
        run: ls -ahl ./build/libs/*.jar
        
## 빌드 아티팩트 업로드
      - name: Upload build artifact for job
        uses: actions/upload-artifact@v3
        with:
          ## 업로드 키 값 (임의지정)
          name: project_artifact
          ## Gradle의 경우
          path: "./build/libs/*.jar"
          
      - name: Create distribute
        run: mkdir ~/dist
      - name: Download build artifact for job
        uses: actions/download-artifact@v3
        with:
          name: project_artifact
          path: dist
          
      - name: Show structure of downloaded files
        run: |
          ls -alh dist
          
      - name: Transfer JAR to EC2 server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          rm: true
          source: "dist/*.jar"
          target: /home/ubuntu/devrun
